'use client';
import {useEffect,useMemo,useState} from 'react';
import {MapPinned,Building2,ClipboardList,Search,Download,RefreshCw,ChevronRight,PanelLeftClose,ExternalLink,Check,Info,Plus,Minus,ShieldCheck,Home,Database} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {candidates,references,parcelLabel,reviewParcels,boundarySource} from '@/lib/candidates';
import {clean,buildingName,housingType,types,countText,uniqueBuildings} from '@/lib/housing';
import addressLinks from '@/lib/address-links.json';
import {SurveyMap} from '@/components/survey-map';
type Household={id:string;parcel:string;building:string;unit:string;status:string;revision:number};
const statuses=['미조사','동의','비동의','보류'];
export default function Page(){
const [canEdit,setCanEdit]=useState(false),[authenticated,setAuthenticated]=useState(false);
const [tab,setTab]=useState('구역·조사대장'),[query,setQuery]=useState(''),[filter,setFilter]=useState('전체'),[selected,setSelected]=useState('214-27'),[surveys,setSurveys]=useState<any[]>([]),[households,setHouseholds]=useState<Household[]>([]),[lookups,setLookups]=useState<any[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[batchProgress,setBatchProgress]=useState(''),[api,setApi]=useState({address:false,building:false}),[lookup,setLookup]=useState<any>(null),[form,setForm]=useState({inclusion:'포함',source:boundarySource,note:''}),[unit,setUnit]=useState(''),[building,setBuilding]=useState(''),[newStatus,setNewStatus]=useState('미조사');
async function load(){try{const r=await fetch('/api/survey',{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw Error(d.error);setCanEdit(d.access?.canEdit===true);setAuthenticated(d.access?.authenticated===true);setSurveys(d.surveys);setHouseholds(d.households);setLookups(d.lookups??[]);setLoaded(true);setError('');}catch(e){setError((e as Error).message);}}
useEffect(()=>{void load();fetch('/api/lookup').then(r=>r.json()).then(d=>{const v=d as {address:boolean;building:boolean};setApi(v);}).catch(()=>{});},[]);
useEffect(()=>{const s=surveys.find(s=>s.parcel===selected);setForm({inclusion:'포함',source:boundarySource,note:s?.note??''});setLookup(lookups.find(l=>l.parcel===selected&&(!l.lawCode?candidates.find(c=>c.parcel===selected)?.dong==='신영동':l.lawCode===candidates.find(c=>c.parcel===selected)?.lawCode))??null);setUnit('');setBuilding('');setMessage('');},[selected,surveys,lookups]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'filter_parcels',title:'지번 조사대장 검색',description:'검색어로 현재 조사 후보 지번과 건물 참고명을 필터링합니다. 구역 편입을 확정하지 않습니다.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(v:any)=>{if(typeof v?.query!=='string'||v.query.length>100)throw Error('검색어 오류');setQuery(v.query);setTab('구역·조사대장');return {query:v.query,scope:'도면 판독 조사 후보'};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort();},[]);
const survey=surveys.find(s=>s.parcel===selected),reference=references[selected];
const filtered=candidates.filter(c=>(parcelLabel(c.parcel)+' '+buildingName(lookups.find(l=>l.parcel===c.parcel),'')+' '+(lookups.find(l=>l.parcel===c.parcel)?.addresses??[]).map((a:any)=>a.road).join(' ')+' '+(references[c.parcel]?.name??'')+' '+(references[c.parcel]?.road??'')).includes(query.trim())&&(filter==='전체'||(surveys.find(s=>s.parcel===c.parcel)?.inclusion??'포함')===filter));
const included=new Set(surveys.filter(s=>s.inclusion==='포함').map(s=>s.parcel));
const scope=households.filter(h=>included.has(h.parcel));const counts=statuses.map(s=>scope.filter(h=>h.status===s).length);const agreed=counts[1];
const currentLookups=lookups.filter(l=>candidates.some(c=>c.parcel===l.parcel&&(!l.lawCode?c.dong==='신영동':c.lawCode===l.lawCode)));
const registryBuildings=[...new Map(currentLookups.filter(l=>!reviewParcels.has(l.parcel)&&surveys.find(s=>s.parcel===l.parcel)?.inclusion!=='제외').flatMap(l=>uniqueBuildings(l)).filter(b=>b.main!=='부속건축물').map(b=>[String(b.id),b])).values()] as any[];
const totalH=registryBuildings.reduce((n,b)=>n+(Number(b.households)||0),0),totalF=registryBuildings.reduce((n,b)=>n+(Number(b.families)||0),0);
const noTitles=currentLookups.filter(l=>!l.buildings?.length).length;
const selectedUnits=households.filter(h=>h.parcel===selected);
async function post(path:string,payload:any){if(!canEdit){setMessage('조회 전용입니다. 관리자만 수정할 수 있습니다.');return null;}setBusy(true);setMessage('');try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d;}catch(e){setMessage((e as Error).message);return null;}finally{setBusy(false);}}
async function saveSurvey(){if(await post('/api/survey',{parcel:selected,revision:survey?.revision??0,...form})){await load();setMessage('조사 내용을 저장했습니다.');}}
async function addUnit(){if(await post('/api/households',{parcel:selected,building,unit,status:newStatus,revision:0})){await load();setUnit('');setMessage('세대를 등록했습니다.');}}
async function statusChange(h:Household,status:string){if(await post('/api/households',{...h,status})){await load();setMessage('동의 상태를 저장했습니다.');}}
async function lookupParcel(){const d=await post('/api/lookup',{parcel:selected});if(d){setLookup(d);await load();}}
async function refreshAll(){if(!canEdit)return;setBusy(true);let ok=0;let failures=0;for(let i=0;i<candidates.length;i++){setBatchProgress(`조회 ${i+1} / ${candidates.length}`);try{const r=await fetch('/api/lookup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parcel:candidates[i].parcel})});if(r.ok)ok++;else failures++;}catch{failures++;}}await load();setBatchProgress(`조회 완료 ${ok}건 · 오류 ${failures}건`);setBusy(false);}
function download(){const rows=[['법정동·지번','편입판단','건물명(주소·대장)','도로명주소','건축물대장PK','주택유형','상세용도','세대수(원본)','가구수(원본)','주부속','조회일','판독확인'],...candidates.flatMap(c=>{const l=currentLookups.find(l=>l.parcel===c.parcel),sv=surveys.find(s=>s.parcel===c.parcel);const bs=uniqueBuildings(l);return (bs.length?bs:[null]).map(b=>[parcelLabel(c.parcel),sv?.inclusion??'포함',buildingName(l),l?.addresses?.map((a:any)=>a.road).join(' / ')??'',b?.id??'',b?housingType(b):'',b?.detail??'',b?.households??'',b?.families??'',b?.main??'',l?.checked??'',reviewParcels.has(c.parcel)?'재판독 필요':'도면 후보']);})];const escape=(v:any)=>'"'+String(v).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';const u=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='신영동일대_주소_건축물대장_조회결과.csv';a.click();URL.revokeObjectURL(u);}
return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><span className="logo"><Home size={22}/></span><span>신영동<span className="brand-sub">마을 조사 워크스페이스</span></span></a><div className="area-label">종로구 · 신영동 214 일대</div><nav>{[[MapPinned,'구역·조사대장'],[ClipboardList,'동의 현황'],[Database,'자료·연결 안내']].map(([Icon,label]:any)=><button key={label} className={tab===label?'active':''} onClick={()=>setTab(label)}><Icon size={19}/>{label}</button>)}</nav><div className="sidebar-bottom"><ShieldCheck size={20}/><strong>{canEdit?'관리자 수정 모드':'공개 조회 전용'}</strong><p>누구나 현황을 볼 수 있으며,<br/>수정은 관리자만 가능합니다.</p><span>너와나 우리마을</span></div></aside><main><header><div><span className="eyebrow">SINYEONG · HOUSING SURVEY</span><h1>{tab==='구역·조사대장'?'구역·주택 조사':tab}</h1><p>지번에서 건물로, 건물에서 세대로.</p></div><div className="header-actions"><div className="access-actions"><span className="access-badge">{canEdit?'관리자 · 수정 가능':'조회 전용'}</span>{loaded&&(authenticated?<a href="/signout-with-chatgpt?return_to=%2F" target="_top">로그아웃</a>:<a href="/signin-with-chatgpt?return_to=%2F" target="_top">관리자 로그인</a>)}</div><span className="stage">공식 API 연결됨</span><Button variant="outline" onClick={download}><Download/>조사대장 내보내기</Button></div></header>
<div className="notice"><Info size={19}/><div><strong>빨간 경계 안을 조사합니다. 필지 수와 가구 수는 다릅니다.</strong><span>사용자가 지정한 빨간 테두리가 조사 범위입니다. 건물명은 주소 API와 대장을 함께 확인하며, 세대수·가구수는 각각 집계합니다.</span></div><button onClick={()=>setTab('자료·연결 안내')}>확인할 자료 <ChevronRight size={16}/></button></div>
<section className="stats"><article><span>도면 지번 후보 · 가구 수 아님</span><strong>{candidates.length}<small>필지</small></strong><p>붉은 경계 내부 포함 · 지번 재판독 {reviewParcels.size}곳</p></article><article><span>조회된 주건축물</span><strong>{loaded?registryBuildings.length:'—'}<small>개</small></strong><p>대장 PK 중복 제거 · 지번 재판독 후보 제외</p></article><article><span>건축물대장 원본 집계</span><strong>{loaded?totalH:'—'}<small>세대</small><em>{loaded?totalF:'—'}가구</em></strong><p>두 항목은 별도 지표이며 더하지 않습니다.</p></article><article className="consent-stat"><span>등록 세대 동의율</span><strong>{scope.length?Math.round(agreed/scope.length*100)+'%':'—'}</strong><p>편입 확인 지번의 등록 {scope.length}세대 기준</p></article></section>
<div className="data-progress"><span>공식 API 조회 {currentLookups.length} / {candidates.length}필지 · 대장 결과 없음 {noTitles}필지 · <strong>실제 거주 가구 총수는 미확정</strong></span>{canEdit&&<Button variant="outline" disabled={busy} onClick={refreshAll}><RefreshCw size={14}/>{busy&&batchProgress?batchProgress:'전체 다시 조회'}</Button>}<span role="status">{!busy&&batchProgress}</span></div>
{error&&<div className="error" role="alert">{error}<Button variant="outline" onClick={load}>다시 불러오기</Button></div>}
{tab==='구역·조사대장'&&<><section className="workspace"><SurveyMap selected={selected} onSelect={setSelected} lookups={currentLookups} households={households}/><div className="detail-panel"><div className="panel-head"><div><span className="eyebrow">선택한 조사 후보</span><h2>{parcelLabel(selected)}</h2></div><span className="badge">{survey?.inclusion??'포함'}</span></div><div className="detail-content"><div className="building-title"><Building2 size={30}/><div><h3>{buildingName(lookup,reference?.name??'조회 전')}</h3><p>{lookup?.addresses?.[0]?.road||reference?.road||'도로명주소 확인 전'}</p></div></div>{reference&&!lookup&&<p className="reference">웹 참고정보 · 공식 API 확인 전 <a href={reference.url} target="_blank" rel="noreferrer">출처 보기 <ExternalLink size={12}/></a></p>}<dl><div><dt>주택 형태</dt><dd>{lookup?types(lookup):(reference?.type?reference.type+' (참고)':'미확인')}</dd></div><div><dt>공동주택명</dt><dd>{buildingName(lookup,'대장 확인 전')}</dd></div><div><dt>대장상 세대수 / 가구수</dt><dd>{countText(lookup)}</dd></div><div><dt>등록한 조사 세대</dt><dd>{selectedUnits.length}세대</dd></div></dl>{canEdit&&<Button className="api-button" variant="outline" onClick={lookupParcel} disabled={busy}><RefreshCw size={16}/>주소·건축물대장 조회</Button>}<span className="api-note">{api.address&&api.building?'인증키 연결됨 · 실조회 가능':'API 인증키 연결 필요'}</span>{lookup&&<div className="lookup"><strong>공식 조회 결과</strong><p className="reference">조회: {new Date(lookup.checked).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>{lookup.errors?.length>0&&<p role="alert">일부 조회 오류: {lookup.errors.join(' / ')}</p>}{lookup.addresses.map((a:any)=><p key={a.buildingId}>{a.road} · {a.name||'건물명 미기재'}</p>)}{lookup.buildings.map((b:any)=><p key={b.id}>{clean(b.name)||buildingName(lookup,'명칭 미기재')} {clean(b.dong)} · {housingType(b)} / {clean(b.detail)||'상세용도 미기재'}<br/>세대 {b.households??'미기재'} · 가구 {b.families??'미기재'}</p>)}{!lookup.buildings.length&&<p>해당 지번 표제부 조회 결과 없음. 부속지번·합필 여부를 확인해주세요.</p>}<small>대장상 0은 해당 항목의 원본값입니다. 실거주 가구 없음으로 해석하지 않습니다.</small></div>}<div className="divider"/><h3>붉은 경계 기준 편입</h3>{reviewParcels.has(selected)&&<p className="feedback">기존 도면의 지번·위치를 다시 확인해야 하는 후보입니다. 편입 상태는 포함이며, 지번이 확정될 때까지 대장 원본 합계와 지도 위치 표시에서만 제외합니다.</p>}<div className="boundary-confirmed"><strong>포함</strong><span>붉은색 테두리 안쪽 · 사용자 지정 기준</span></div><p className="reference">지번 판독 상태와 편입 여부는 별도로 관리합니다.</p>{canEdit&&<><label>조사 메모<textarea placeholder="필지 분할·합병, 현장 확인 필요사항 등" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><Button className="primary" disabled={busy||!loaded} onClick={saveSurvey}><Check size={16}/>조사 메모 저장</Button></>}{message&&<p className="feedback" role="status">{message}</p>}<button className="text-link unit-link" onClick={()=>setTab('동의 현황')}>이 지번의 세대별 현황 <ChevronRight size={16}/></button></div></div></section>
<section className="table-panel"><div className="panel-head"><div><h2>지번별 조사대장 <span className="count">{filtered.length}</span></h2><p>한 필지가 한 건물 또는 한 세대를 뜻하지 않습니다.</p></div><div className="table-tools"><div className="search"><Search size={17}/><Input aria-label="지번 또는 건물명 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="법정동·지번·건물명 검색"/></div><select aria-label="편입 확인 필터" value={filter} onChange={e=>setFilter(e.target.value)}>{['전체','포함'].map(v=><option key={v}>{v}</option>)}</select></div></div><div className="table-scroll"><table><thead><tr><th>지번</th><th>건물명 / 공동주택명</th><th>주택 형태</th><th>대장 세대 / 가구</th><th>편입 확인</th><th>정보 수준</th><th/></tr></thead><tbody>{filtered.map(c=><tr key={c.parcel} className={selected===c.parcel?'selected':''}><td><button onClick={()=>{setSelected(c.parcel);window.scrollTo({top:250,behavior:'smooth'});}}>{parcelLabel(c.parcel)}</button></td><td>{buildingName(currentLookups.find(l=>l.parcel===c.parcel),references[c.parcel]?.name??'조회 전')}<small className="road-address">{currentLookups.find(l=>l.parcel===c.parcel)?.addresses?.map((a:any)=>a.road.replace('서울특별시 종로구 ','')).join(' / ')}</small></td><td>{types(currentLookups.find(l=>l.parcel===c.parcel))}</td><td>{countText(currentLookups.find(l=>l.parcel===c.parcel))}</td><td><span className="badge">{surveys.find(s=>s.parcel===c.parcel)?.inclusion??'포함'}</span></td><td><span className="source-tag">{reviewParcels.has(c.parcel)?'지번 재판독':currentLookups.some(l=>l.parcel===c.parcel)?'공식 API 조회':'조회 대기'}</span></td><td><button aria-label={`${c.parcel} 상세보기`} onClick={()=>setSelected(c.parcel)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">검색 결과가 없습니다. 지번 또는 검색 조건을 바꿔주세요.</div>}</div></section></>}
{tab==='동의 현황'&&<><SurveyMap selected={selected} onSelect={setSelected} lookups={currentLookups} households={scope} consent/><section className={'consent-layout '+(!canEdit?'readonly-consent':'')}><div className="table-panel"><div className="panel-head"><div><h2>세대별 동의 현황</h2><p>편입 확인 지번의 등록 세대 기준 · 법정 동의율이 아닌 조사 집계</p></div></div><div className="status-grid">{statuses.map((s,i)=><div key={s} className={'status status-'+i}><span>{s}</span><strong>{loaded?counts[i]:'—'}<small>세대</small></strong></div>)}</div><div className="progress-track">{counts.map((n,i)=><span key={i} className={'status-'+i} style={{width:scope.length?`${100*n/scope.length}%`:'0%'}}/>)}</div><div className="consent-note">전체 대상 세대수가 확정되기 전까지 등록 세대 동의율만 표시합니다. 다가구의 가구수, 건축물대장 세대수, 권리자 수는 각각 다를 수 있습니다.</div><div className="panel-head"><h3>{parcelLabel(selected)}</h3><select aria-label="세대 조회 지번 선택" value={selected} onChange={e=>setSelected(e.target.value)}>{candidates.map(c=><option key={c.parcel} value={c.parcel}>{parcelLabel(c.parcel)}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>건물 식별명 / 동</th><th>세대 식별값</th><th>동의 상태</th></tr></thead><tbody>{selectedUnits.map(h=><tr key={h.id}><td>{h.building}</td><td>{h.unit}</td><td>{canEdit?<select aria-label={`${h.unit} 동의 상태`} value={h.status} disabled={busy} onChange={e=>statusChange(h,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select>:<span className={`consent-label consent-${statuses.indexOf(h.status)}`}>{h.status}</span>}</td></tr>)}</tbody></table></div>{!selectedUnits.length&&<div className="empty"><ClipboardList size={36}/><h3>등록된 조사 세대가 없습니다</h3><p>{canEdit?'확인된 동호수나 세대 식별값을 등록해주세요.':'관리자가 조사 결과를 등록하면 지도와 현황에 반영됩니다.'}<br/>동의/비동의/보류는 제공받은 조사 결과로만 입력합니다.</p></div>}</div>{canEdit&&<div className="detail-panel"><div className="panel-head"><h2>세대 등록</h2><Plus size={18}/></div><div className="detail-content"><p><strong>{parcelLabel(selected)}</strong></p><label>건물 식별명 / 동<Input value={building} onChange={e=>setBuilding(e.target.value)} placeholder="예: 건물 A / 가동"/></label><label>동호수 또는 조사 세대 식별값<Input value={unit} onChange={e=>setUnit(e.target.value)} placeholder="확인된 호수·식별값 입력"/></label><label>동의 상태<select value={newStatus} onChange={e=>setNewStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><p className="reference">실명·연락처·주민등록번호는 입력하지 마세요.</p><Button className="primary" disabled={!loaded||busy||!unit.trim()||!building.trim()} onClick={addUnit}>세대 등록</Button>{message&&<p className="feedback" role="status">{message}</p>}</div></div>}</section></>}
{tab==='자료·연결 안내'&&<section className="sources"><div className="table-panel"><div className="panel-head"><h2>정확한 조사에 필요한 자료</h2></div><div className="source-body"><div className="source-row"><span className="step">01</span><div><h3>구역 내 편입 필지 확정</h3><p>사용자가 제공한 붉은 테두리 안의 식별된 지번은 포함으로 반영했습니다. 지번 판독이 불확실한 7곳도 편입과 구분하여 재판독 표시만 유지합니다. 북서쪽 일부 필지는 구기동에 속하므로 실제 법정동으로 조회합니다. 도면 지번의 오독·누락과 현재 분할·합병 여부를 계속 대조합니다.</p><a href="https://www.eum.go.kr/web/gs/gv/gvGosiDet.jsp?seq=610064" target="_blank" rel="noreferrer">종로구 제2025-48호 고시 확인 <ExternalLink size={14}/></a><p>열람·문의: 종로구청 주택관리과 · 02-2148-2612</p></div><span className="badge">빨간 경계 적용</span></div><div className="source-row"><span className="step">02</span><div><h3>주소 API 연결</h3><p>도로명주소, 지번, 건물명, 건물관리번호를 조회합니다. 주소 검색만으로 구역 경계나 세대수를 확정할 수 없습니다.</p><a href="https://business.juso.go.kr/" target="_blank" rel="noreferrer">주소기반산업지원서비스 · 검색 API 신청 <ExternalLink size={14}/></a></div><span className="badge">{api.address?'연결됨':'승인키 필요'}</span></div><div className="source-row"><span className="step">03</span><div><h3>건축물대장 조회</h3><p>건축HUB 표제부로 건물명·주용도·세대수·가구수를 확인합니다. ‘빌라’라는 이름만으로 다세대·연립을 결정하지 않습니다. 한 필지의 복수 건물 및 부속지번을 추가 대조해야 합니다.</p><a href="https://www.data.go.kr/data/15134735/openapi.do" target="_blank" rel="noreferrer">건축HUB 건축물대장정보 서비스 신청 <ExternalLink size={14}/></a></div><span className="badge">{api.building?'연결됨':'인증키 필요'}</span></div><div className="source-row"><span className="step">04</span><div><h3>세대별 조사 결과 반영</h3><p>확인된 건물·동호수를 등록하고 동의·비동의·보류를 관리합니다. 미제공 데이터는 미조사로 남깁니다. 전체 대상과 법적 권리자 명부가 확정되기 전에는 이 비율을 법정 동의율로 사용하지 않습니다.</p></div><span className="badge">자료 수령 대기</span></div></div></div><div className="data-principles"><h3>현재 데이터의 범위</h3><p>도면 판독 후보 {candidates.length}필지 · API 조회 {currentLookups.length}필지 · 실제 거주 가구 총수 미확정</p><p>도면에서 읽기 어려운 지번, 도로, 분할·합병된 필지 등이 누락되거나 잘못 판독되었을 수 있습니다. 주택만을 확정한 목록이 아니며, 각 행의 검토 상태는 별도로 저장됩니다. 건물명은 주소 API 명칭을 우선 표시하고 대장 명칭을 병기합니다. 두 자료 모두 명칭이 없으면 “명칭 미기재”로 표시합니다. 이는 건물이 없다는 뜻이 아닙니다.</p><p>업로드 TXT: 서울 전체 {addressLinks.totalRows.toLocaleString()}행 중 신영동 {addressLinks.areaRows}행의 지번 연결정보를 반영했습니다. 이 TXT에는 도로명·건물명·세대수가 없어 공식 API로 보완합니다.</p><p>인증키는 서버 비밀 설정에 저장되어 있습니다.</p></div></section>}
<footer><span>신영동 주택·동의 현황</span><span>사용자 지정 경계 2026.10.03 · 주소·건축물대장 API 조회</span></footer></main></div>;
}
