'use client';
import {useEffect,useRef,useState} from 'react';
import {parcelLabel,candidates} from '@/lib/candidates';
import {SurveyUnit,unitMatchesParcel} from '@/lib/unit-inventory';
const statuses=['미조사','동의','비동의','보류'];
export function UnitTable({units,selected,onSelect,canEdit,busy,onChange}:{units:SurveyUnit[];selected:string;onSelect:(p:string)=>void;canEdit:boolean;busy:boolean;onChange:(u:SurveyUnit,s:string)=>void}){
 const [all,setAll]=useState(true),[query,setQuery]=useState(''),[status,setStatus]=useState('전체');
 const previous=useRef(selected);useEffect(()=>{if(previous.current!==selected){previous.current=selected;setAll(false);}},[selected]);
 const missing=candidates.filter(c=>!units.some(u=>unitMatchesParcel(u,c.parcel))&&(all||c.parcel===selected)&&(!query||parcelLabel(c.parcel).includes(query.trim())));
 const rows=units.filter(u=>(all||unitMatchesParcel(u,selected))&&(!query||(u.parcels.map(parcelLabel).join(' ')+' '+u.building+' '+u.unit+' '+u.road).includes(query.trim()))&&(status==='전체'||u.status===status));
 return <><div className="panel-head unit-toolbar"><div><h3>호수별 조사 목록 <span className="count">{rows.length}</span></h3><p>API에 기재된 호수와 조사용 번호를 구분합니다. 호수 교차검증 상태는 각 행에 표시합니다. 같은 건물의 부속지번은 한 번만 집계합니다.</p></div><div className="table-tools"><label><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/> 전체 지번</label><select aria-label="세대 조회 지번" value={selected} onChange={e=>{onSelect(e.target.value);setAll(false);}}>{candidates.map(c=><option key={c.parcel} value={c.parcel}>{parcelLabel(c.parcel)}</option>)}</select><input aria-label="호수별 목록 검색" placeholder="지번·건물·호수 검색" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="호수별 동의 상태 필터" value={status} onChange={e=>setStatus(e.target.value)}>{['전체',...statuses].map(s=><option key={s}>{s}</option>)}</select></div></div><div className="table-scroll unit-scroll"><table><thead><tr><th>지번</th><th>건물 / 동</th><th>호수</th><th>확인 근거</th><th>동의 상태</th></tr></thead><tbody>{rows.map(u=><tr key={u.id}><td>{parcelLabel(u.parcel)}{u.parcels.length>1&&<small className="road-address">연결 지번 {u.parcels.filter(p=>p!==u.parcel).join(', ')}</small>}</td><td>{u.building}<small className="road-address">{u.road.replace('서울특별시 종로구 ','')}</small></td><td><strong>{u.unit}</strong><small className="road-address">{u.floor}</small></td><td><span className={'unit-source '+(u.official?'official':'provisional')}>{u.official?'API 기재 호수':'조사용 번호'}</span><small className="road-address">{u.source}</small><small className="road-address">{u.detailCheck??'상세주소 미조회'}</small>{u.warning&&<small className="unit-warning">{u.warning}</small>}</td><td>{canEdit?<select aria-label={`${u.building} ${u.unit} 동의 상태`} disabled={busy} value={u.status} onChange={e=>onChange(u,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select>:<span className={`consent-label consent-${statuses.indexOf(u.status)}`}>{u.status}</span>}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">확인된 호수 또는 대장 수량으로 생성한 세대가 없습니다. 아래 수량 미확정 지번도 확인해주세요.</div>}</div>{missing.length>0&&<div className="inventory-issues"><h3>세대수 미확정 지번 · {missing.length}곳</h3><p>대장 수량이 0이거나 대장이 없고, 지번 확인이 필요한 곳입니다. 실제 주택이 없다는 뜻이 아닙니다. 세대수 합계에는 포함하지 않으며, 확인된 세대는 관리자 등록으로 추가할 수 있습니다.</p>{missing.map(c=><button key={c.parcel} className="text-link" style={{marginRight:16,marginBottom:12}} onClick={()=>{onSelect(c.parcel);setAll(false);}}>{parcelLabel(c.parcel)} · 수량 확인 필요</button>)}</div>}</>;
}
